# Generated by Django 3.0.8 on 2020-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200813_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
