# Generated by Django 3.0.8 on 2020-08-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, verbose_name='Основной')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_main',
        ),
        migrations.CreateModel(
            name='Is_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Main')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='main_or_not',
            field=models.ManyToManyField(through='articles.Is_Main', to='articles.Main'),
        ),
    ]
