# Generated by Django 3.0.8 on 2020-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200813_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='main_or_not',
        ),
        migrations.AddField(
            model_name='tag',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.DeleteModel(
            name='Is_Main',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
