# Generated by Django 3.0.8 on 2020-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200814_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Scope',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='main',
            new_name='is_main',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='tag',
            new_name='scope',
        ),
    ]
